# Generated by Django 2.1.7 on 2020-04-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200423_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='tEmail',
            field=models.CharField(max_length=40),
        ),
    ]
