# Generated by Django 2.2.10 on 2020-11-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
