# Generated by Django 2.1.7 on 2019-12-03 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminID', models.CharField(max_length=20, unique=True)),
                ('adminName', models.CharField(max_length=20)),
                ('adminEmail', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePreRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=10, unique=True)),
                ('courseTitle', models.CharField(max_length=10)),
                ('courseCredit', models.IntegerField()),
                ('level', models.IntegerField()),
                ('term', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SemesterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesterCode', models.IntegerField(unique=True)),
                ('semester', models.CharField(max_length=10)),
                ('totalSection', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Courses')),
            ],
        ),
        migrations.AddField(
            model_name='coursepreregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Courses'),
        ),
        migrations.AddField(
            model_name='coursepreregistration',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.SemesterInfo'),
        ),
        migrations.AddField(
            model_name='coursepreregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo'),
        ),
    ]
