# Generated by Django 2.1.7 on 2020-10-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePreRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=5)),
                ('paymentStatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=20, unique=True)),
                ('courseTitle', models.CharField(max_length=100)),
                ('courseCredit', models.IntegerField()),
                ('level', models.IntegerField()),
                ('term', models.IntegerField()),
                ('totalSection', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSection', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentStatus', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesterCode', models.IntegerField()),
                ('semesterTitle', models.CharField(max_length=20)),
                ('regOpenDate', models.DateField()),
                ('regCloseDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WaiverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=40)),
                ('existingWaiver', models.IntegerField()),
                ('specialWaiver', models.IntegerField()),
                ('totalWaiver', models.IntegerField()),
                ('amountofWaiver', models.IntegerField()),
                ('percentofWaiver', models.IntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.SemesterInfo')),
            ],
        ),
        migrations.AddField(
            model_name='remarks',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.SemesterInfo'),
        ),
        migrations.AddField(
            model_name='remarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.SemesterInfo'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.SemesterInfo'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.SemesterInfo'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo'),
        ),
        migrations.AddField(
            model_name='coursepreregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered', to='adminpanel.Courses'),
        ),
        migrations.AddField(
            model_name='coursepreregistration',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.SemesterInfo'),
        ),
        migrations.AddField(
            model_name='coursepreregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentCredits', to='student.StudentInfo'),
        ),
    ]
