# Generated by Django 2.1.7 on 2020-04-22 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepreregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered', to='adminpanel.Courses'),
        ),
        migrations.AlterField(
            model_name='coursepreregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentCredits', to='student.StudentInfo'),
        ),
    ]
