# Generated by Django 2.1.7 on 2020-04-27 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200425_2008'),
        ('adminpanel', '0002_auto_20200423_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=500, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.SemesterInfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo')),
            ],
        ),
    ]
