# Generated by Django 2.1.7 on 2019-12-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20191203_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepreregistration',
            name='paymentStatus',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
