# Generated by Django 2.1.7 on 2019-12-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_coursepreregistration_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterinfo',
            name='semesterCode',
            field=models.IntegerField(),
        ),
    ]
