# Generated by Django 2.1.7 on 2020-04-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_courses_totalsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseTitle',
            field=models.CharField(max_length=100),
        ),
    ]
