# Generated by Django 2.1.7 on 2019-12-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20191211_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepreregistration',
            name='semester',
            field=models.CharField(max_length=20),
        ),
    ]
