# Generated by Django 2.1.7 on 2020-04-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20200428_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseCode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
