# Generated by Django 2.1.7 on 2020-05-02 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_merge_20200428_2226'),
        ('adminpanel', '0006_auto_20200428_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.SemesterInfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo')),
            ],
        ),
    ]
