# Generated by Django 2.1.7 on 2020-05-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_courseregistration_waiverinfo'),
        ('adminpanel', '0007_waiverinfo'),
    ]

    operations = [
    ]
