# Generated by Django 2.1.7 on 2020-05-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_courseregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=40)),
                ('existingWaiver', models.IntegerField()),
                ('specialWaiver', models.IntegerField()),
                ('totalWaiver', models.IntegerField()),
                ('amountofWaiver', models.IntegerField()),
                ('percentofWaiver', models.IntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.SemesterInfo')),
            ],
        ),
    ]
