# Generated by Django 2.1.7 on 2020-05-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_merge_20200506_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='registered',
        ),
    ]
