# Generated by Django 2.1.7 on 2020-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_remove_courseregistration_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
