# Generated by Django 2.1.7 on 2020-05-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_waiverinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiverinfo',
            name='student',
        ),
        migrations.AddField(
            model_name='waiverinfo',
            name='studentID',
            field=models.CharField(default=11, max_length=40),
            preserve_default=False,
        ),
    ]
