# Generated by Django 2.1.7 on 2020-05-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_paymentinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='student',
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
