# Generated by Django 2.1.7 on 2020-05-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_paymentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
