# Generated by Django 2.1.7 on 2020-05-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_coursepreregistration_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepreregistration',
            name='registered',
        ),
    ]
