# Generated by Django 2.1.7 on 2019-12-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorName', models.CharField(max_length=20)),
                ('advisorID', models.CharField(max_length=20)),
                ('advisorEmail', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=20)),
                ('courseTitle', models.CharField(max_length=30)),
                ('courseCredit', models.CharField(max_length=20)),
            ],
        ),
    ]
