# Generated by Django 2.1.7 on 2019-12-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseTeacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisor'),
            preserve_default=False,
        ),
    ]
