# Generated by Django 2.1.7 on 2019-12-14 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stID', models.CharField(max_length=20, unique=True)),
                ('stName', models.CharField(max_length=30)),
                ('stEmail', models.CharField(max_length=30)),
                ('stGender', models.CharField(max_length=6)),
                ('stPhone', models.CharField(max_length=20)),
                ('stPassword', models.CharField(max_length=30, null=True)),
                ('stAdvisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherInfo')),
            ],
        ),
    ]
