# Generated by Django 2.1.7 on 2019-12-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='stPassword',
        ),
    ]
