# Generated by Django 2.1.7 on 2020-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_studentinfo_stpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='stGender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='stPhone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
