# Generated by Django 2.1.7 on 2020-04-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200425_2003'),
        ('student', '0003_auto_20200425_2008'),
    ]

    operations = [
    ]
